node {
    stage('Clone Repository') {
        checkout scm
    }

    stage('Build Image') {
        withCredentials([string(credentialsId: 'nuget_apikey', variable: 'apiKey')]) {
            imageName = "ap_ipg_sample";
            version = "1.${currentBuild.number}";
            app = docker.build("${imageName}:${version}", " --build-arg VERSION=${version} --build-arg APIKEY=${apiKey} .");
        }
    }

    stage('Removing Container') {
        sh "docker stop ${imageName} || true && docker rm ${imageName} || true";
    }

    stage('Running Container') {
        app.run(" --name ${imageName}");
    }

    stage('Connecting to Networks') {
        sh "docker network connect nginx ${imageName}";
    }
}
